spring:
  config:
    activate:
      on-profile: supabase
  datasource:
    url: ${SUPABASE_JDBC_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: app_users
